### ISSUE TITLE
The C# Demo can't build: library CSharp.Basic is missing

### ISSUE THREAD

**Issue by cg-zhou** [TOSUN-Shanghai/libTSCANDemos#2]
It seems that the library CSharp.Basic is not open source, where can I retrieve it?

![image](https://github.com/TOSUN-Shanghai/libTSCANDemos/assets/9943470/4b0133e4-59db-4a13-96d0-52198d0ca70c)

**Comment by TSSkyhits** [comment]
[CSharp.Basic file.zip](https://github.com/TOSUN-Shanghai/libTSCANDemos/files/13256944/CSharp.Basic.file.zip)

**Comment by TSSkyhits** [comment]
[CSharp.Basic file.zip](https://github.com/TOSUN-Shanghai/libTSCANDemos/files/13256957/CSharp.Basic.file.zip)
