### ISSUE TITLE
Get System Clock Frequency

### ISSUE THREAD

**Issue by davidkirchner** [TOSUN-Shanghai/libTSCANDemos#4]
I have configured a CANFD channel with the `tscan_configure_canfd_regs` function on a **Tosun TC1011**.
By experimenting with the configuration and counter-checking it against another CANFD controller, I was able to work out that the system clock frequency is 40MHz. Is there a way to get the system clock frequency with the libTSCAN API, or is the system clock frequency the same for all Tosun devices?

**Comment by TSSkyhits** [comment]
The system clock frequency is the same for all TOSUN Devices.

**Comment by davidkirchner** [comment]
Great, thanks!
